---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: grafana-admin-secret
  namespace: monitoring
  annotations:
    reflector.v1.k8s.emberstack.com/reflection-allowed: "true"
    reflector.v1.k8s.emberstack.com/reflection-allowed-namespaces: "monitoring"
    reflector.v1.k8s.emberstack.com/reflection-auto-enabled: "true"
spec:
  encryptedData:
    admin-password: AgBoWovtIB2JKJ84Zj3vvDC9bJyZ9c5ocpFS3rShl4zMtLwfJEmSsaKbE6OZkD3QgYIyJlRkfYRIvyBJgMDFmFr/+TAB+hTHzzyJOw+fLwHfdPgQSaM7qcuCPPcFd8Fa5PbNnwnD4w/LUNayPmi9HVHUNZWgXhJ4Fj1m4ik6JrlC5s5K1QbHxGEfpde2iDC9iynb60K8rNXJU6kU6Qd/vyCDIFEtqenw/d5m7A7/x3ODz+Xl0jz4/xLED8IWwu1PpTr8A0efkFnIjYHvJBvY6OB+Bk5Cc3Oc3RC592FvaW0mOSCvgqxZ93eGXaUUBheXZN+FF/PsV/R4ZN5Xqay3duNvAgwhP191gq/UE0Dcc3S4PPg1IyNJhXeSzjAwEFFBY/I+hJGgg4zLwh+wfvls5UQTpl9Ci4W3s0OULkcop9aM8ZSsfmMZRhhNmGVo3RbbBA3dgiQqkqNCW3OfJu80hjr8UqMuxumJvUmjLWg8yNnhwpYpa9Ckwjl2OPIGD/hHHQKLYG+BpJN5J1c93smkkfdx+wxobF/HBu0AsDawstxgPwyYi7DRy+GHY242vKPeIIyBrZdCGrj+VHCGyGilyEGyQF0sA/2wlkW67jWMv7bn4ZvaiQG2FD32YAIeJOE0h2B/Th8M5HhRQENfN2xKlAcpby6Ui2VzXjVNG4bkM3TgqYaXgQQKNXecCanIQiPEqlIkmk3Pho09uw==
    admin-user: AgCs8H8nm8E4L6YgvA+6ysSz9pIsBBrsB5SogPmfMVve9u9GWNPtHDC0FGN8sglrgEtKyItqbnm//DBtJCGenb4vOC3thZw2PEPjWfqaCZ36KSPumVVHBw+qFxM5iPLrU1hptMa3CKa+SLtjprQ9c1JRXQQukPvGl4lT/vvLa6OItWdOkGnfZC99RuCD43uEljJRc/I+X0kJK4uD0cwUxfTfwRezlX43EeoK7N8SMlFgDupg0CWP/IPBtAseHrUUuQG/lYzROvSmFRjZWm8MJ8qti9Zlr3WAwZ9ThjZlnnLY5/N4b0ziJYEb6s0IcASM0a1SQDKz6BjyIR81jsImNv4AVSMa3dVJt03xf+erZ9WQkHS8FsT2oBviTje8FuCWKbydCuxGC5UlJ8Dsl1jGt/uByHVWm4/GbY6KIOoawwTFf/PrxW+zVFAdfvM/3Egrvt1c3FogrllFg7WvNEEcoyd/M6iI52OMu1YXMIDcXSACoa1A3lMopW9JO5KRvxGeVMjcidmiAxO5pn2EGNlCphiXI5fOeigWb8pw7dEqNixCkCvVHqK7rAjWwMjgkT3uFLLNRQDyOEoa8Sb1sV8i4pkFbl4a8OTyLYExffwRfulkxNUwFE6+H9iPzvqJXJamnc48lKuDiLAqt+9y2gsBWCsyZFsjF4ggVYqwjC4TKpGikPMvsCbVd0OQ6WWbAKVTWExvO4HQnw==
  template:
    metadata:
      name: grafana-admin-secret
      namespace: monitoring
      annotations:
        reflector.v1.k8s.emberstack.com/reflection-allowed: "true"
        reflector.v1.k8s.emberstack.com/reflection-allowed-namespaces: "monitoring"
        reflector.v1.k8s.emberstack.com/reflection-auto-enabled: "true"
