---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: postgresql-secret
  namespace: database
  annotations:
    reflector.v1.k8s.emberstack.com/reflection-allowed: "true"
    reflector.v1.k8s.emberstack.com/reflection-allowed-namespaces: "workload"
    reflector.v1.k8s.emberstack.com/reflection-auto-enabled: "true"
spec:
  encryptedData:
    postgresql-admin-password: AgArzQQRSQweg266Rzkx4uDNh59GLBuLHB/2GLddp2fLTW2RwTTDm1ppbutMgw5HntXNm2l5B5a8eHPJMlt4dtjL19AjWWoxniSfDXQ4gkXlioXqVSaqBJzIBXf3AfBxvofP9MZ1pclnkPWSTQMeRhsuJjjs3pVj7nrDVk5mYlHykGjQW9R3GKwceIGyvgZRiXTpfM4zmpvgmmKOHmegQzO/n0SuNXjHX6mXIzw939sRgQbbeCXEAtKxEZ/xoomFH3QHStLsdH6j7WetSGKt0cCmj2lt3iBuf2Q9gnLJ1VKupdkn9rlk4m4Eje95X7Z306S54q2YnkpND+Af1kQMegsk10tWH9JUd91tV7kN2OyosCwgRjqsD1IA0T8xi0AGG8+nio5izZzFWBcur5Lx6Qs5ZIedFPTrFeWAoTI4KFvCHPOmX5/UfCWgYxeH4AZLm4Dia9iGI/D6KNswmacY9lbW02+5axG6UpcDGRpdnLA02xtzym3yT6XC15eyFR3haYI0x2xnco3T+O4LkZJcrs0EQ9kThLOZXypXXJ6Js5USyJXbiFgeQfQxTsn9QvSHGHzT5jYDgzYlPMI3OdieVCREH8BQo2ZZJvYADhPTQqkoHcOSVXBoakYjPIQOokqhLvmKg8gAJoYCR7iaTP2Ry7XP4XPI5IOCSMqIPYiwc7y3q1jr59Isyw2wISk9dTDXDo/rL0dpKQVsCyk/Ziy7Zvp6WcqkFhJ8rYEegl1rTupEo/puGNzq1weRO/daEQ==
    postgresql-immich-password: AgC7Uw/dQxOz8+B0DiJQjrXy5K8jV4kvGJ4VEETuMZ2fKtkPZCzLtOuUj4S5oItdc8aC1BQjVDjTPRfgXjL34Bas9uh19OKio9j1sF+zXUxSp+ZJLR6i3WL+czMAseE5sts9xFE8A+iXLZ55FLnQ6EXpqVbGXhYfTA+UB6iUBjt/2H4glDrd+tsbkigBjnatQ4s6Ay5nIA9VO0jmkgvg5tFaYluz6QfGs4uS/HC3q0dwvML2CgQ+n/thANqFniMROHK1iYMS2N14C+Wa3WQVaufPSUOch+TA9V0s3tT/+ENUiBrd/tN2E4stB7mjvTiMgGvSdVJZOd/XCcAdKMf2EAZ/J0wcUDz17uBlBXTKislads1DfStn8pzYz+9yUgPoopQhXMObV8wAzkrVKYM8X9GjamvCfahrY1RYDLr5Ov7j/w9nP03Z9ayE/fHZkEpdatTgpzet8ephtKICF1Pbl3nsaJ3nddpnzbKgwR5piHVyNppLukaaXxw/mug1X4P2xcv13nND4ELuEyXXXqECem2GG6GHzEW+T5wI5NTck1J2r/yE7fOBTNKBMbadPEBLdDn6TVgila2Bg90W/HGsURunK1NMH0W7UGLEVW0AnZKj/34Eqw8AptGL0BrCceHDcT51IQUTi8GW8uaWSJzSs2XkAdXNwri36h9jVb9PofAylJ2g6hDjoUWQld0uCpKCQERS1uRYkBALYU9VUAfXx4zVXqku+ThhzcYxBlOjT+mcjEYkqwz7DHv89R2/cw==
  template:
    metadata:
      name: postgresql-secret
      namespace: database
      annotations:
        reflector.v1.k8s.emberstack.com/reflection-allowed: "true"
        reflector.v1.k8s.emberstack.com/reflection-allowed-namespaces: "workload"
        reflector.v1.k8s.emberstack.com/reflection-auto-enabled: "true"
