---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: traefik-secret
  namespace: infrastructure
spec:
  encryptedData:
    users: AgANIw2NU8EtbxDyZpB2LjgHLtpnHOVQCK5tsHQVu7eDExjdoj2Ht5ND6Wk/Q4zGWxa7eiGKA9a9N3nc9Gnxbt6ZZy+5dyGGOzt3LZxBt2mD12Wt6tqD6Q9kX1gWRWnl4i1mcRUVBwm9BjDGLFDG6/Y2wf3c0zPTjoeUrk0RJ8mjS7I2/ekcgLRsaQ0aHPL1XDHJXeY6OKhWkuiLMBffWh0qizX9LdgvWIhR5sYfN1jeqI+lsZ0zY+Zum0gryUFGQvOUtTSyJCwxgSBTXWT6SddHyVWhP+K0Ws60PZfbk0yQ9eEU7G57R3YYZTR1TWn7L3hp27zaIxv3jPtH7RIlPYSgjVdzy4qnnK4Y+gVOxE3xyoaH+8ULr20uVh8DgRXuSbXDTU0ioaLRGA/yt/Y1EnDayoD2E4ooquRJI2hqbTTqcWxtq8cj7mk6Qkx5dU+bvbriqJq/8bgoG3FGRjBzCtOSdWq47y1nLJe5J8hlMHyK0FLg5NbmgkyqotZgyrkqCY1Z+2ki+Rb2uIY7fEb/ePwiw2hua6VlgrUinrpBJOhKr5WWZfp5zYdIgQUD0JzYNavQmS5H0WlDCLaBLD5i7He3GvOZ1aOcElN6NPchsWHiNKzyj8/jZqPgeuNjiub8zb4M8/Ea/JjB6o9q5H+izYwKriXf/tXLvQU1vBUOg/AtEK9fmH2UhXpmF5o7Mp/QIDuuYs7zi4d+AKuJ23oXuaxhMWY5nJIaMr6rjzmfVDzlxk8sWdCl7f4=
  template:
    metadata:
      name: traefik-secret
      namespace: infrastructure
