---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: infra-docker-config
  namespace: infrastructure
  annotations:
    reflector.v1.k8s.emberstack.com/reflection-allowed: "true"
    reflector.v1.k8s.emberstack.com/reflection-allowed-namespaces: "default,workload"
    reflector.v1.k8s.emberstack.com/reflection-auto-enabled: "true"
spec:
  encryptedData:
    .dockerconfigjson: AgAyuAHl3zm+KNPJho02fRawEwoqrgrMHPLeOYJo4RGWGip1rklJAMUfh/HOze9sl6IgNTvnSsqQAMZ3RO+5UwoQxa85bC0B9PdBFxNY5V1MfKrtXRY8yVhZEkWTISYN8MQITGbpROuqOqiiGHO0wJUUl+io56WS5UPJ3XNNvK4oXP04N+K0gwxvLZ/zGz0fafVOHIt9Ogxe6BZSv6Mmk0eAdox/anO4mCllLgTkjGK0F+8sZT8HlVrfARXEg4UT/6FyUwTz3lohBdy+TY6wmOtJxj01jAwJ0iRvEDj7b6Oi4DoihK0OvIxFFbLPvsbcu7VAgOSzgvgCL4f0jYn8CGT0YGHhEZ6h6MTh8n2J6KVE/hnSa+GB9/NKlbtknC+jnx4RZNqEF//QyjcK9foiI9Qhm0aCqo5g0Pl3N4GpExog86Fg5im7637fBO9N3CPkdI8+GNvth1lm4ItbeZLb3ovCWjDYGcBXmFsS//H4u1JRALh7Fe+4WFtODpuGGGBJm7hOXmIvqRVcKNDB0sk1y12kbAblQfmsovcmBY2fyUSUHWnvjm46/QmoPf21JTRGw4ZnWxDa5dZPd8H8odT6IwYMynMRbD9DkC04q6dCMf0D49bJw7JS0UZaSh0BeaiSVy54OlsqD1micKC47mTX3c9rfBwaMuaS84yWvfJL5ml08ifzlfaFRKsk7+RvR+Mp6XxhaapCuHbDY53HZW0gHJjJ31TKV+nkUmhRN0IX6U0StGZ0Jgwov/ET5gcwgoCNONRrXzidRtDnbggmDbLNBxWnRNsYKb68hgfhqLqEpWF6EPdSwj6BOGrnM3Q1/wPB8I3mUi07Ba6sgjZa2ziIBX2ccDSKkg8qXxES5UuQHpLa+0f/FbwyFnfaLnSt9a3ZFxMic4uV41gGMZwyzWt9seSOdeiw/cuBtiuThlJWvUTVyx4ZmA8N2GcKSYW9BUHleYBCDfmwEunITGCSiVop8uASVLHeFHSJAQd6Lz9V1p02Bhba9JeTNhRAvcOJLPYtwo5OXA==
  template:
    metadata:
      name: infra-docker-config
      namespace: infrastructure
      annotations:
        reflector.v1.k8s.emberstack.com/reflection-allowed: "true"
        reflector.v1.k8s.emberstack.com/reflection-allowed-namespaces: "default,workload"
    type: kubernetes.io/dockerconfigjson
