apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-cm-ghaap-secret
  namespace: argocd
data:
  url: https://newyeti.qzz.io
  application.instanceLabelKey: argocd.argoproj.io/instance
  server.insecure: "false"
  server.secure.protocol: h2c
  server.x_forwarded_proto: "https"
  server.disable.auth: "false"
  accounts.ghapp: login=ghapp
  account.ghapp.tokens: $ghaap-auth-secret:githubAppID!$ghaap-auth-secret:githubAppInstallationID!$ghaap-auth-secret:githubAppPrivateKey
