apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: monitoring
commonAnnotations:
  argocd.argoproj.io/sync-wave: "2"
helmCharts:
  - name: nri-bundle
    repo: https://helm-charts.newrelic.com
    version: "7.0.18"
    namespace: monitoring
    releaseName: newrelic-bundle
    valuesFile: values.yaml
