---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: ghcr-auth-secret
  namespace: default
spec:
  encryptedData:
    .dockerconfigjson: AgAZpWJxJESmiIN65KCHSsugDpgdOfWOZmiiRBVhIQV/XTBhFh9GBL7l7fLv7D83jy2smg+FpYdNR2TphmxsQoKs30R0e0K85i/iG6uoJKMXc43P1+cEQThXh29FgPfjLdctcsa4ZgPT7vVSv4OXOn23+xZ0glYrHrDEUH4U9NWT9FSc3axdB1nqRb8MK4gtaKtJv1nSPFPck7k5JixfCL2gnNO8QAb/AK9zYg5lEr86IR5cSQ/jXUu3LzrQ/k1nm+kxBZsjwdUI9sIlUnbi2M6CKSgevqXwI8Jw/EA4nL/TofLH8PtHe9wIw+2fack1dEvM5pyHBaVXIDC5UjOp5liqU1tkhrQYrFNIAwA0S+RzoGJectXsez7GgyBVnTU34CsoMs2q0tOQFlFzRH1zfTq4rNVMftltXpKaIUGkzyQEhhyv4RcXb9pqQeDMLkFxWaeP67KgFyuYpS0jy42Ifpg/bB8ZnbvCPoNy7n47keWKInPDem0TT8GVa7+FUYJbg0uwdNbwLF0QOl5K9RrONJkqg6FqsUA8bV0yDAnh7b7POdEHphRtHp4eulpLYN+o88RNmzE8Z8WsxV1nhXS833HJavhWH4CD7aoW1IDl2Ry7oni1lQqkr2HPifIm4yE3tZrvkYIWomkpm65rUYpBQ+9QjvNzXsU7XBiUgNSMlXl1o6qTjuaRT5VZeaVMcTnp+niV82xO23quspc54jDttHmI1q+74VmCvKSRL4Gq5ES3TwHO39QqrY1j/1NrsMBY1/IjnZ8NKq9+Ow8art9cK7cbGeqOu3IUO6rpMNlKzuQye9P6MnGfpKucIRmpuagvFfTsX39HwRm9EtlKkbQp3IRMVWbMLaCOVZLd0sir7hbZcdTwLjilqdq1/BDbY8TfPmf7J3TiJnCExjn8YjUzMaW0jALlWNN31CQguOXddjhGTAcKqO3A8CsKoQ0BjXNM6TFLrGaD1rISx9/2vUpnV1DNnYSaviBhv/znpSvz4kBUMHZApedax+yW3hHkTEYUpPs=
  template:
    metadata:
      name: ghcr-auth-secret
      namespace: default
    type: kubernetes.io/dockerconfigjson
