---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: ghcr-auth-secret
  namespace: argocd
  metadata:
  annotations:
    reflector.v1.k8s.emberstack.com/reflection-allowed: "true"
    reflector.v1.k8s.emberstack.com/reflection-allowed-namespaces: "*"
spec:
  encryptedData:
    .dockerconfigjson: AgCu9rTpVJpdM/nU9fH1RHYWmPd71fjAwE491i3jK/mEQu+kXq9R6Q/s6+24NAOLqRoB8fO7woazOZyF8hyP3ggyKqkqFibcJnnLoa3VXQN2n0dDcpiph8L2iIMDRp2RQT4V8G+OcGWshG/518eS5+PT/UxdItNqK/ciGZPRy4w699ltgGGqxW0Abj2497g5+dGSExFwp6ENqMRve6YaZFr+vtqLG5hGGX4R3QdbCVZFq5wLx+QS7GZGAd1zKFvbkBDLIhxBFnoQ1PEYboB92pDk5aHarzIGOOUdEikro31QLBxOQQeRQczXtfiPenR/rPiY7v1U2gVT0DvEtnvDYJqIAcyGcD0O8cNKI63FsEgynvHLuCSHT5i419IWZONsnPNpOCmT3teh6m7bQkFz62/Awb9/b4sbZ0G95NXQCnjTkRL4koky6Wmqj8nEk+phBfZ1g74QBs37OSyDJx/w/UZOg93pmuAcySVoLOxib2ldkU30XLu+2vK8NOe0wA92fz1T3dJfpRuzL+y1sbPOrmd10lKc6ri10sB9bW/D4VwEGM/yui4rCmQ7OBeD7cAalE9OqSkQytj69ZUXa28xx871OOnEzDWkC9dx7b4by63RUm05OQBzEBP9k7tppnB5p0Df0sIGaYtmEyx297h6W3IKbewCiWXLrsazEIhZpl6fIto6Kc0rW6N886NZsUIqN9Pddnh8uSdJOSz1P8LF+lU0Sgtra9MQgCdv3UJtMDgFXCc9Xgz82RJtz3McCrKpJpUAvBUDOgjdgsk9H8RuFwNqvlCjkcVw+hAeNEpLM2VCMKTlqYody0rSLXRoXhNQp0YwEJ3Mjya45eYuGMnMWnw5yH3U0YkCCUSIEiyb8HHWEr/qVp+M5HrtM2LZQMOe0hec8vDoOTLelfm3iJUMnMu9Q+ze2hzTfh7yKb619pDmUeHj/6PwVLrl2l+hQOSGkMo5aasT83k2njtbdWBMArBce0SI6nFmhMmfG6ZEWNHH0+BB09DDyRdVT7/UHLQGGwiGXA==
  template:
    metadata:
      name: ghcr-auth-secret
      namespace: argocd
    type: kubernetes.io/dockerconfigjson
