---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: ghcr-io-secret
  namespace: dev-microservice-app
spec:
  encryptedData:
    .dockerconfigjson: AgA5FM5f4JRmWTrNO29sECa5T/5Qr/FUUv/0KGqciElHlwqJtlljOAcQX/IMeNCTm3VJV7iAqqRw6dddUNMA2VruBIKm5Z0QNfx0CTmeUwZDS3035wc5moEblQHq0wkVRPmNAH/yPZh30FTS+ctlL/0F4DA47IrYbPvS8IKSIV8vOFt3SpNG48Fhix7i3I6yBnWwuh8ts2b2bcVyr9kH++qvPR8/vFTaRG2XAR2bopk5Hv7jDZ45xNT714hxtSGSnn6Ze5wXWjs0i8WIBU99iwvsk1r1NFlEMSP+qRq4X8Y+93MdBdiw+KnfZxphfifLb2GMtkhTx6A/WXnf/yz+pA00Z3+1OV+vTY1iigbxgZwMpJZtwZkxk0RITU5Rh/2P+6lF98crDJ7G5BkcoOob1rbGeJ8FbfZcf3KDra5x+bDQYb9zHDBjbHm5YQ9l9DJQ0JG78mzw4Ya2qi3LrzWEZFMT7ekbVW4Q6nC6dNxH2AlzqQJGrX3gnldXPRh3HDvIN1wiKVPcJePGmO7m5GO96HZY9+bX8VBnRj/9pZ9JVD3xNUKMFyrm7EkLQu8YWDTbVbyyloNZwmHBRCOrvgzsOxlov1S6rxaL6cNuPjps9XlABxPrkxOWjBshfOpJh9Iq9Ne9furZuea4owwRJt2diRL7VRiHBAiShyvVcZ9qvxzqR4/9GLVWsO93ctj7s/07xDWNswsoKNXYlQw9IDMqkkH53CER68A7PIxIjxJ/5KSTXeHqojqHUnZ3OFjbWf8TJNuln+YmbHd7Takfcd2yACh/ZBcFoyPnrWeB3VG5DWDofBu+oTBjd+vd0/dulaZp6qtPDwg6jFezCykALLJfjiw+4SVGMab114vqb8r3FmpOKotm3plkR+hE2GBiLpz5gtTR49WBEjnj4w7aNrsiVL1r4Y/b+AE4V6aZneNFXOgGs/ZQcDC3s+ZlmJ97lLwdmRJ3yzKqBaLn9+odR4pKzn1ToNq5ifG4MgzZ+tPVHz5kf9zuM08qQKyi1xWU8OBcHf9/bj0=
  template:
    metadata:
      name: ghcr-io-secret
      namespace: dev-microservice-app
    type: kubernetes.io/dockerconfigjson
