---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: ghcr-auth-secret
  namespace: microservice-app
spec:
  encryptedData:
    .dockerconfigjson: AgBcYfoGED+hY5yk4SWhude2RaL5jbzuD+S7wuTrKLtY2e2LeQIo0B8p9BmK5qrnWXwjz2NMUl4Y/QaH32XfHlV/JXclD55T+tyAdEigw/WOQ7CkKrKF5jdIFWUxyYVprlWiq/rM76X84vN5uh6xUGUeIfIrVwnolW8Zgwn55oJTToLLLlddkWusNEU4JP4MmjRdmFXOMK5F5+0ABu4ACykMUdS8Lzrz9tQRGCQ1gh6skOOtJqP+Xb8tsVf2Wehf20GgkLCqYgmnn2cahcBlGPIHh/RDwM+hJUortfPiBd9WIjAOEX48kmuprpTuCqOdNlYgK54iLUYpS8iOS/pX7Zp85U1RW27CYfxtWEQ5NdlczDX/bSCqrHRdcdrV9Lr9yR8XYehAgnMjbkw8F+P4SES67lCmqtwDovO25NTN3OjWQ1BodORphFYrKNYQuJZMfRSvX7z9yrk0xzgaflACgGXgdqkYz9Sz+uZieNghEPG6l9FMpXPd0DewmoNcs7GG3Iv5SvchIxB/Ob+uWoQo8G1Qei6URgr9nMaVi5KHqqRGgTLUzy0KDZ3WEkVTVsCM0ScNGZ9PLaqGA/Z2yPZRIJmWhfAgIsUMT5t6LlB71r1a34ZNPyBH0hZqOZdehSozBqC3fHxAhlHcRrCDtf2yL4wbLHRN8R/nkMU8emfa+ctFSbSUgsjghMvSlpvtDaTRdDjHWniUJuGJmUgw9KBcrJUKURDo5Bg17oBY6Wf6Mi3/IBlRObYe2bPsUS0PTEhy3rBwhD2sSouUHjs95XWKKPHtM3xr19iwZwoGNdNaJR+myN2peNXM2dfj7R8MsS2UozLje+eoIxRYILXrayMnF0oTOQK0OSNdQhNV/ugMju0bWYGVtVEG8Mg2pG/Evy/lArdEU1BT7tk2JCXxVJtefTLZmNZukw234t2Z9XhRcY9AcCEvkdqX+L/epiwm5mq8+sSUvSu1P9HMW7WwOVv50dbNfgK31BqfaAMp1atmCY1c5ky4QKCR6D8UQ8iMV7eKoM0pGQ==
  template:
    metadata:
      name: ghcr-auth-secret
      namespace: microservice-app
    type: kubernetes.io/dockerconfigjson
