---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: github-ssh-key
  namespace: argocd
spec:
  encryptedData:
    ssh-privatekey: AgBwUlrZNqhQc7ORevwyH0QKlzdVyE6D8qSt0V+9Kk8FRRqnvv6wAjYPimeFiPZUAq5HSVSECPRWGuc9HlUrLH9YXPV9zVyrdERjZ6AMXNUsDwTkTKY5T9E0MmGTK9d8HrRLk8LQ40gHaJ5JHsTVa7sBdwSGc6+KcMC+CHyICqtRNCDEJOKSD189G/RcUl9yptkN8GbAtokuarCF1AXoZx8qRAgC6Px/+aeqf3ClAYtDhjmkCuFmDKfkCuaw9Q4elDTzPIDhjo2oLPARdQOfKocjzazpCw6YL1jFixWgPk3c6JCs31rc+s5BxgR/iOKhgW5Cr3MDBVfxkC8OuS8yRlzfZ741yLO6DVXJesGVLmRf49bzth7DFldFIA/+/WiCECImMBbqZ/NPAAlvTKyLca0Q5ZRXtpB9nTzSQDxtiYErQaYfXVtYAFKjfWWVRw/Iygk/LJPjqQWCaZpvUPcLBWU5yiSCKK7vXbD3rw8BRety85dxQiId59ebVEh4X4gauOTYx9rJ3mi8HKZTaRj17kIbp5LBjK6If3yOLMLGab/kjr3FrPGuSasYPIElKN3tGY19ky0mupCzIOwmFquBwIl9aK/j4LD4oI1sY4sHgfHhwStUjQ6onCtv53ij7bEZe6Z474btgMC30qrK7r67RV7UOX/H7eGqPkFwZreQmZN4FqGJvsQXXyKsgv9jcAQP2Qum1/+zA56/asWLa5eYyEZyLZzz6/4ZuUzDCP52DYWJlGUQqaCJ/JTghTqyCXuTAtyLnpQa9mwxDQhtQNNqGfl37Q+dxfQnnn5PGwfJMF9E4CnURy8FE2Wjyg67lxRXvPjf+88rscXwW25oqGeGMrLl4ieGLqi1D/0dYVD04tWAyAmHUrU/kSN6RjiH5Iog+SdB5B1P2wNhz2ThxVL5p92qtVNqfQLEYnpOMzW9Yz1hRbhUVuWLe7N36XD7zbhPQbNPBm8kyy+ntoicGex7I39gcqFi3jcJeR/mXXzp1CfL1YzkH6EedlJXUu4zq4wV95+Ivv0Tb7k52ZKRRd799AvOAg4/5lonOygwMrydWCP5O6Ap+zms/7g6tTAZVCJE/oI8N1+RK23DwLZKrwyGJY/1wzKeZ0SCbNND0PA/PtKlLbptP1hVhZRVbCv/PMKaQIyUatMIXu+XbT8nsAyG1NBxR7RimmDZ5+6RDIt33xJIXvKcLxqw1U7vfWWMxsJPGQuPKmbAhSt1vsQoZf0Ipnb8VBy5qsluco78BpnW0wrc8ohK2A==
  template:
    metadata:
      name: github-ssh-key
      namespace: argocd
    type: Opaque
