apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonAnnotations:
  argocd.argoproj.io/sync-wave: "3"
resources:
  - ../../base
  - ingress-routes.yaml

patches:
  - target:
      kind: Deployment
      name: traefik
      namespace: traefik
    path: traefik-deployment-patch.yaml
  
  - target:
      kind: Service
      name: traefik
      namespace: traefik
    path: traefik-service-patch.yaml
  
  - path: traefik-config-patch.yaml
    target:
      kind: HelmChart
      name: traefik