apiVersion: v1
kind: Service
metadata:
  name: traefik
  namespace: traefik
spec:
  type: NodePort
  ports:
  - name: traefik
    port: 8080
    targetPort: traefik
    protocol: TCP
    nodePort: 30420
  - name: web
    port: 8000
    targetPort: web
    protocol: TCP
    nodePort: 30480
  - name: websecure
    port: 443
    targetPort: websecure
    protocol: TCP
    nodePort: 30443
