apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonAnnotations:
  argocd.argoproj.io/sync-wave: "3"
resources:
  - ../../base

patches:
  - target:
      kind: Deployment
      name: grafana-alloy
      namespace: monitoring
    path: grafana-alloy-patch.yaml