apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../prod

patches:
  - target:
      kind: Deployment
      name: sealed-secrets
      namespace: kube-system
    path: tolerations-patch.yaml