apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonAnnotations:
  argocd.argoproj.io/sync-wave: "2"
helmCharts:
  - name: alloy
    repo: https://grafana.github.io/helm-charts
    version: "1.5.1"
    namespace: monitoring
    releaseName: lgtm-distributed
    valuesFile: values.yaml