apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: dev-appset
  namespace: argocd
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
  - git:
      repoURL: https://github.com/schmhj/cluster-config.git
      revision: HEAD
      directories:
      - path: apps/*/values/envs/dev
  
  template:      
    metadata:
      name: '{{index .path.segments 4}}-{{index .path.segments 1}}'
    spec:
      project: default
      sources:
        - repoURL: https://github.com/schmhj/microservice-template.git
          path: helm/microservice
          targetRevision: HEAD
          helm:
            valueFiles:
            - $values/apps/microservice-template-app/values/common/values.yaml
            - $values/apps/microservice-template-app/values/envs/dev/values.yaml
            
        - repoURL: https://github.com/schmhj/cluster-config.git
          targetRevision: HEAD
          ref: values
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{index .path.segments 4}}-{{index .path.segments 1}}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
        retry:
          limit: 5
          backoff:
            duration: 5s
            maxDuration: 3m0s
            factor: 2