apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: workload-appset-dev
  namespace: argocd
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
    - git:
        repoURL: https://github.com/schmhj/cluster-config.git
        revision: HEAD
        directories:
          - path: apps/workloads/*/overlays/dev
    - git:
        repoURL: https://github.com/schmhj/cluster-config.git
        revision: HEAD
        files:
          - path: "{{.path.path}}/config.json"
  template:
    metadata:
      name: "{{index .path.segments 2}}-dev"
      namespace: argocd
      annotations:
        argocd.argoproj.io/sync-wave: "5"
      labels:
        layer: "3"
        env: dev
        domain: workload
    spec:
      project: workload-dev
      sources:
        - repoURL: https://github.com/schmhj/cluster-config.git
          targetRevision: HEAD
          path: "{{.path.path}}"
        - repoURL: https://github.com/schmhj/cluster-config.git
          targetRevision: HEAD
          ref: values
        - repoURL: { { .chartRepo } }
          targetRevision: { { .chartVersion } }
          chart: { { .chartName } }
          helm:
            valueFiles:
              - $values/apps/workloads/{{index .path.segments 2}}/base/values.yaml
              - $values/apps/workloads/{{index .path.segments 2}}/overlays/dev/values.yaml
      destination:
        server: https://kubernetes.default.svc
        namespace: workload
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
          - ServerSideApply=true
          - SkipDryRunOnMissingResource=true
        retry:
          limit: 5
          backoff:
            duration: 5s
            maxDuration: 3m0s
            factor: 2
