apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: workload-appset-dev
  namespace: argocd
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
  - matrix:
      generators:
      - git:
          repoURL: https://github.com/schmhj/cluster-config.git
          revision: HEAD
          directories:
          - path: apps/*/envs/dev
      - git:
          repoURL: https://github.com/schmhj/cluster-config.git
          revision: HEAD
          files:
          - path: "{{.path.path}}/config.json"

  template:
    metadata:
      name: "{{index .path.segments 2}}-dev"
      namespace: argocd
      annotations:
        argocd.argoproj.io/sync-wave: "5"
      labels:
        layer: "3"
        env: dev
        domain: workload
    spec:
      project: workload-dev
      destination:
        server: https://kubernetes.default.svc
        namespace: workload
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
        retry:
          limit: 5
          backoff:
            duration: 5s
            maxDuration: 3m0s
            factor: 2
  templatePatch: |
    spec:
      sources:
        - repoURL: '{{ .chartRepo }}'
          targetRevision: '{{ .chartVersion }}'
      {{- if .isGitRepo }}
          path: '{{ .chartName }}'
      {{- else }}
          chart: '{{ .chartName }}'
      {{- end }}
          helm:
            valueFiles:
              - $values/apps/workloads/{{index .path.segments 1}}/base/values.yaml
              - $values/apps/workloads/{{index .path.segments 1}}/overlays/dev/values.yaml
              
        - repoURL: https://github.com/schmhj/cluster-config.git
          targetRevision: HEAD
          ref: values
        - repoURL: https://github.com/schmhj/cluster-config.git
          targetRevision: HEAD
          path: '{{ .path.path }}' # This points to apps/*/envs/dev/
          directory:
            include: 'docker-config-mirror.yaml' # Only pick up the secret mirror
