apiVersion: v1
kind: Secret
metadata:
  name: ghcr-auth-secret # Must match the source name or be mapped
  namespace: microservice-app
  annotations:
    # Tell Reflector where to pull the data from
    reflector.v1.k8s.emberstack.com/reflects: "argocd/ghcr-auth-secret"
data: {} # Leave this empty; Reflector will populate it