- op: add
  path: /spec/template/spec/tolerations
  value:
    - key: "tier"
      operator: "Equal"
      value: "infra"
      effect: "NoSchedule"

- op: add
  path: /spec/template/spec/nodeSelector
  value:
    tier: infra