- op: add
  path: /spec/template/spec/tolerations
  value:
    - key: "tier"
      operator: "Equal"
      value: "infra"
      effect: "NoSchedule"

- op: add
  path: /spec/template/spec/affinity
  value:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: tier
            operator: In
            values:
            - infra