apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonAnnotations:
  argocd.argoproj.io/sync-wave: "2"
resources:
  # Format: git::https://github.com/org/repo.git//path/to/chart?ref=main
  - git::https://github.com/schmhj/microservice-template?ref=main

helmCharts:
  - name: microservice-template
    repo: https://github.com/schmhj/microservice-template.git # Git repo URL
    version: main # Branch/Tag
    path: helm/microservice # Internal path to the Chart.yaml
    releaseName: microservice-template
    valuesInline:
      fullnameOverride: microservice-template
      replicaCount: 2
      imagePullSecrets:
      - name: infra-docker-config
      image:
        repository: ghcr.io/schmhj/microservice-template
        pullPolicy: IfNotPresent
        tag: "latest"
