apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonAnnotations:
  argocd.argoproj.io/sync-wave: "2"

helmCharts:
  - name: microservice
    repo: https://ghcr.io/schmhj/charts
    version: "0.1.0" # Branch/Tag
    releaseName: microservice
    valuesInline:
      fullnameOverride: microservice
      replicaCount: 2
      imagePullSecrets:
      - name: infra-docker-config
      image:
        repository: ghcr.io/schmhj/microservice-template
        pullPolicy: IfNotPresent
        tag: "latest"
