# Minimum Traefik configuration for dashboard via NodePort
dashboard:
  enabled: true

service:
  type: NodePort
  nodePorts:
    traefik: 30280

globalArguments:
  - "--global.checknewversion=false"
  - "--global.sendanonymoususage=false"

additionalArguments:
  - "--serversTransport.insecureSkipVerify=true"
  - "--api.dashboard=true"
  - "--api.debug=false"
  - "--log.level=INFO"
  - "--accesslog=true"

