apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonAnnotations:
  argocd.argoproj.io/sync-wave: "2"
# helmCharts:
#   - name: simple-go
#     repo: https://akuity.github.io/demo-helm-charts
#     version: "0.2.1"
#     namespace: workload
#     releaseName: simple-go
#     valuesInline:
#       fullnameOverride: simple-go
#       replicaCount: 1
#       service:
#         type: NodePort
#         port: 30280
#       appconfig: |
#         {"spec":{"stage":"dev"}}

