global:
  postgresql:
    auth:
      username: app_user
      database: app_db

primary:
  resources:
    limits:
      cpu: "250m"
      memory: 256Mi
    requests:
      cpu: "250m"
      memory: 512Mi

metrics:
  enabled: false
