apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: data-storage
  namespace: workloads
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: oci-bv-free
  resources:
    requests:
      storage: 50Gi
