apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonAnnotations:
  argocd.argoproj.io/sync-wave: "2"
  
resources:
  - ../../base

patches:
  - target:
      name: sealed-secrets
      namespace: infrastructure
      kind: Deployment
    path: sealed-secret-deployment-patch.yaml
