apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../prod


patches:
  - target:
      kind: Deployment
      name: cert-manager
      namespace: cert-manager
    path: tolerations-patch.yaml

  - target:
      kind: Deployment
      name: cert-manager-webhook
      namespace: cert-manager
    path: tolerations-patch.yaml

  - target:
      kind: Deployment
      name: cert-manager-cainjector
      namespace: cert-manager
    path: tolerations-patch.yaml
