apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-prod
  annotations:
    argocd.argoproj.io/sync-wave: "0"  # Deploy first
spec:
  acme:
    email: sachindra.maharjan@outlook.com
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      # cert-manager stores the ACME account private key here
      name: letsencrypt-prod-account-key
    solvers:
      - dns01:
          cloudflare:
            email: sachindra.maharjan@outlook.com  #Cloudflare account email
            apiTokenSecretRef:
              name: cloudflare-api-token-secret
              key: api-token
        # Scope this solver only to your zone
        selector:
          dnsZones:
            - "qzz.io"