apiVersion: tailscale.com/v1alpha1
kind: Connector
metadata:
  name: immich-connector
  namespace: workloads
spec:
  hostname: immich
  appConnector: {}
  exitNode: false
  tags:
    - tag:k8s-operator
