apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonAnnotations:
  argocd.argoproj.io/sync-wave: "2"
resources:
  - ../../base
  - reflector-deployment-patch.yaml

patches:
  - target:
      kind: Deployment
      name: reflector
      namespace: kube-system
    path: reflector-deployment-patch.yaml
