- op: replace
  path: /spec/replicas
  value: 1

- op: replace
  path: /spec/template/spec/containers/0/resources
  value:
    requests:
      cpu: "50m"
      memory: "64Mi"
    limits:
      cpu: "100m"
      memory: "64Mi"
