apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonAnnotations:
  argocd.argoproj.io/sync-wave: "2"
helmCharts:
  - name: reflector
    repo: https://emberstack.github.io/helm-charts
    version: "10.0.16"
    namespace: infrastructure
    releaseName: reflector
    valuesFile: values.yaml
