apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: workload-prod
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  description: "Workload Environment"
  sourceRepos:
    - "*"
  destinations:
    - namespace: "*"
      server: "https://kubernetes.default.svc"
    - namespace: "*"
      server: "https://129.158.33.235:6443"
  clusterResourceWhitelist:
    - group: "*"
      kind: "*"
  destinationServiceAccounts:
    - server: https://kubernetes.default.svc
      namespace: "*"
      defaultServiceAccount: kube-system:argocd-cluster-admin
    - server: https://129.158.33.235:6443
      namespace: "*"
      defaultServiceAccount: kube-system:argocd-cluster-admin