---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: cloudflare-api-token-secret
  namespace: infrastructure
  annotations:
    reflector.v1.k8s.emberstack.com/reflection-allowed: "true"
    reflector.v1.k8s.emberstack.com/reflection-allowed-namespaces: "cert-manager"
    reflector.v1.k8s.emberstack.com/reflection-auto-enabled: "true"
spec:
  encryptedData:
    api-token: AgAWWHuC4ow7xL1/4MAJqJWBWj0SrHilOaZf5SV9AaMfGJLqhzjoz9dP/MZXDZGexoOIC4oB7ji6+Rc/nQkDP798o+HYJVD2Fsjy1t3Cst/CjJSHSmShU1D5X7GPoudwLHfIkXVEe+z9zreE67bOAHJGdp3tVxc8pSVlH3MZVbJDXxCWZUZ9AZjzwousweB3cx8FbLGhRy6ltDNuwOBtMNvTuW4xgXms4WpQAvQxUkAF/h/OlRE+Wj8og8y5LRDKzyi82uk17GGf8tDLAFIMip8Tz06Jbj0Sx72hhBK1r4vdMOYdjkLIYahAMI6xI3UgmN4zyHJmxxzplq7nK+He55qGmoSmIsQEuF6ke4E3GJlTLChHAUwNqfgv0supcMilBC3aGEc2Klhfy1BeFJdvLwnWysztmRehEULlmvoyinMg46cUQJHyVYK2yOki/Ar/9wHyxCloP7Mutrz9qITznXipW0XsHzs0NmEW8hoyFDWEOizeZOk+ovpqMyaDSADL13CRFWigpjtW6gMadMKSMbFcEayNrpqKHDr7XjLUtOXfg1XbydV90yz+yjg8jkguPsIq4Yfbgu7aYOXEHr0j4Y3PzJZkZdqFmKmxEE3rL5uLwFR6TVMez19Nke9Y8E4QxPONs1s4f+ghtf2EvU55xQalbTgvTcNyfB5cdqqupE4YevjjQid8vhSBdrNuz+v9Bd/EClTs4ve5VTc+7fV+v0BRU/JIxFA2u/MWUeoBNwzDM2U8yTBAuirAyPAejHO2AOVpzJwBCQ==
  template:
    metadata:
      name: cloudflare-api-token-secret
      namespace: infrastructure
      annotations:
        reflector.v1.k8s.emberstack.com/reflection-allowed: "true"
        reflector.v1.k8s.emberstack.com/reflection-allowed-namespaces: "cert-manager"
        reflector.v1.k8s.emberstack.com/reflection-auto-enabled: "true"