---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: infra-docker-config
  namespace: infrastructure
  annotations:
    reflector.v1.k8s.emberstack.com/reflection-allowed: "true"
    reflector.v1.k8s.emberstack.com/reflection-allowed-namespaces: "workload"
    reflector.v1.k8s.emberstack.com/reflection-auto-enabled: "true"
spec:
  encryptedData:
    dockerconfigjson: AgAMoPXcMaTDh.PM8vc5VQLy4EV75yvDmXbAc4OlHs/BdX/rt7JZoGf9E/r+V1I4hCXojojurAmTDP/0ev6B4vT/+O0dE75o7ZOBULD1KkeRHJ792989qbgKd3pWNZnF2G7gkHvVMSrwzBvODP8vBoCewPxZoGcrzqeb0aQ67JiwZpBU2DqgKKG9xRI0lPrq4GwEivr6MNXAS+gfHoICLCB+z8ysdzPLDk44MUa213h4nEI2utrEq/1qkwAjKSPncEJENYJXg6jj2i0IJEHV8XwUWtH1d4zulGPsI7ffCox+EO/PM3brLM/Z/oIjLBcFzNPC41XKz6j/nXQFWkci9j+d+vTxw4uw4cJbU7h/SA1uiySRNtHCjdHVZzmxcqmg8GiSOIprz61Fbjr4qo4g48CFSlpj07fg1IPjixA2DJvixQs5KPSdLQRTpoIZRklF+zpVFzW/muSNYmtABbrKVyrhhhkZZJrCIUyvHwnU9Q6Gm3rf7d/u+OPTiYf+IdeT5V4u2kp1XlFVLNoTXkflY4fyP/Kul0kEv4SHfMURp+6ab+jBiwc6hxC/70nb4HdQte7wSJWzjrff7O6e1x77KIIGq+/7m/t0f7bv+5pjvhSechs5dkoT21jWey7HTiuWnXptCVuxlkmzQbjtN/txEw4hvvNKa8hVcgHEPP9SC6gx8Pb2x+oSx3qTCJk01+CxNC2K2haIJRChxFwsabYl7x7o7Z7xyhY2ABAHwpM1Q3rO2+pKnscsGWE8rjBNCR4g+1wAQIwihuFs/rkvIUb7ZPMb3hFxQn/bfWltr6BVQg53VT2N5U1yNHeLZ0DPSksVHkMAvF0oOlC5EIpQLIaNlPnTi/YfVSL0dSFSx3jiAgZzH6N5gFbRjCKCHX7IcGE6cdK667gQoEr4Sf6ArKZuTIU9orTriG/OQYHnHTZKq0i+6n/dUIf4fJGtBMcoGmBJm4aXzwft+Tqx6SQU3Aitozv8AGkVY0cKEEn6ZehN2nNR5gz0mY6cOCgZ9jOGO/ZNH7kJxbQ==
  template:
    metadata:
      name: infra-docker-config
      namespace: infrastructure
      annotations:
        reflector.v1.k8s.emberstack.com/reflection-allowed: "true"
        reflector.v1.k8s.emberstack.com/reflection-allowed-namespaces: "workload"
        reflector.v1.k8s.emberstack.com/reflection-auto-enabled: "true"
    type: kubernetes.io/dockerconfigjson
