---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: infra-docker-config
  namespace: infrastructure
  annotations:
    reflector.v1.k8s.emberstack.com/reflection-allowed: "true"
    reflector.v1.k8s.emberstack.com/reflection-allowed-namespaces: "workload"
    reflector.v1.k8s.emberstack.com/reflection-auto-enabled: "true"
spec:
  encryptedData:
    dockerconfigjson: AgAHUsYy5/we5pNrzxjhKtZgMcop2J1lFy9G9tQUWJ2AzJBzm7UuiSevgMpQe1uHcYpy9FGDb92Ge+jbiV4MXBwbos3rCA4e2zFi5B5114PhVdzxTshxAyEGzbyp4EJwhml3XJQNekFEjs4TQ/YejQO+iFEhrr6cO/ssDmSQsXlQ5SAFccq2jbPUYKGQWra2Gr675/VfGQIJ7je8yjWU8KmqUkmuM5jHU7Ih6rxs2AneJYfOZzVknOeNxKPJO6/b3aWAPKYLAv5iY0wTJyD6t4XtRDbOFdqePx02qnOcEhmPQZ7ZWYCdUSJTQrRk3IqXdbtcE2Bi6uZIA4TpguPE2HOFU3kU/xHaFeRfmpmAIUkM2c1WBf8YfVSO5rIONxq40St8a5Z9JfdMHk6rgREzmFDT3+FA/SlNnEW30OrVKCRTZCSn7WkLnRa1aaWsa9x0x3JIUOiaXrdOqkn0+cakyOx4S8pmRL9fJ+SgScX3m07Hh0dhqfgubE43LfrgH5GsdrPMtxknqz4SnnUsygOrATZR//YUhhYw233KndcyvkjNOPZmSYF0z6XcZ9GqSFEyQGNnD8tLx3/4ryLkKjyXNvFsM677gTLIEcHfNzsjEN6N5YlHYnKCt1QzS0b/kqgYkwogU914hlfSiyGB7kPthFbiyWZ6on6xyzZ1+GX3yaSy++ICuLUoNUYWmlChZrsJlFPYAlouVzHRyo3y1r7mVNQYmqOpKcmTeXtdazfMohEhtd3DvLBJatxnMpITyCwBpOxYx4EXFu5GZd8jd1lAXBffjMx5ccEM8BpYBvTKmktFPE/O68xQ1ITUiDt9Ed/Jp8Mc92AVcGvEvpEv10IuToGSMlwF83nIDU8HThbKnFXGpyW1fmnYOd8Z6q6FpBJMh8IjP7oB7bJqzr7JdgasEE7GhNU2BW90lwpB3JH761LWCBnqCbndGPWhnc+PgXze2f8QFAl7+TnapbtW4Ub04jC/BXBS3w2zpJ+Pu5OtRyJl9KWN7hZhDctBRmFRy30nyUqx4g==
  template:
    metadata:
      name: infra-docker-config
      namespace: infrastructure
      annotations:
        reflector.v1.k8s.emberstack.com/reflection-allowed: "true"
        reflector.v1.k8s.emberstack.com/reflection-allowed-namespaces: "workload"
        reflector.v1.k8s.emberstack.com/reflection-auto-enabled: "true"
    type: kubernetes.io/dockerconfigjson
