---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: newrelic-secret
  namespace: infrastructure
  annotations:
    reflector.v1.k8s.emberstack.com/reflection-allowed: "true"
    reflector.v1.k8s.emberstack.com/reflection-allowed-namespaces: "monitoring"
    reflector.v1.k8s.emberstack.com/reflection-auto-enabled: "true"
spec:
  encryptedData:
    licenseKey: AgCacacJCXJlVLS9o+Mi1SvSmDMVXP1Bczj+sc9nCSsrLtkFdq5jpN5k9/FH9nfxBKPCzxO9Y797R/z+SY2d37IhtfwlGiztXX7739I8G4gX4ERLj1AMu6tMhJ0MNrmQfwX1Ps56yImFcSFVHzxISF6FFpfRlAobuv4bnv+u9MDS2yi9LXql5j+hg8mMAjEDzwB00UvFBPM8u0obCurRlmFVZUlDBTsARXOE6SMHN2T1Lgah7xULsMtQUiCwOFOdAWVkn8JbaXgzUqagB2GdvcZZR/tVYpSWP/pl7t7qjWmWdeSs0ABNRT6v8UfaqYFIMyUMNO1wWj+3QJedLjBgO6eXTSYbGt1WAfk7P3fN1nmyIHTrXi3LmcR3Qkh1v54N5Dn+30tk7oJHPs0XMSIyIjZMZrmPBcC6/ay79V1ULiN+M60DT4QnZPxCRVg/zChO9kZTZCDZtZlLNk7VB6gA3DNS5SwiLOi0ewfAul7FLfT4tSsT46QshGLYHc4t7yYfq+VPyiPDlng27rt2NZpcmefbNNiXUt3Q/jhy9Zq3c6UQnqm3G08RsjaV6CvR1lHlBDG0hsQyHwjjhNM/Un/htmxEjsA4vldgQBhJyVC12eNlj33AgSKMrVvZORR/+UQNiAYX817zvA3v1sMz89TKHoNFvEHLdSnfAva21f0tAyr2hE3MP6IO0+ppWbBo1fYGSQhSu56Pome6nNbg9TBB4PTksxCchhO6/anyuy6dj1VZXAXQvg8wwhle
  template:
    metadata:
      name: newrelic-secret
      namespace: infrastructure
      annotations:
        reflector.v1.k8s.emberstack.com/reflection-allowed: "true"
        reflector.v1.k8s.emberstack.com/reflection-allowed-namespaces: "monitoring"
        reflector.v1.k8s.emberstack.com/reflection-auto-enabled: "true"
