---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: newrelic-secret
  namespace: infrastructure
  annotations:
      reflector.v1.k8s.emberstack.com/reflection-allowed: "true"
      reflector.v1.k8s.emberstack.com/reflection-allowed-namespaces: "monitoring"
      reflector.v1.k8s.emberstack.com/reflection-auto-enabled: "true"
spec:
  encryptedData:
    licenseKey: AgAwmpHQT6KVLP8w7FfWVUqjWwwZONl5eZQuhplUeEkNe+fcP3b24MnwewPGBtZF4oP51NYX0oYfPKe83EFYnjKK4TqmjEVFsQsk3SzJbHG/8y67yOheu/oS3IE/AYvzB2bLxtSsvPWB9JFC8fTQPO96KRVdDWkNuaLEQ4LLpvdTudwyJWSg16hRim21Gi5Od6GbCOXQoadddpBEkVhXpytCkmzuTyCdGGYXKCw6bAHI/vvsCD7kpX9E7K4gwTkQAdtSaTWZ43Sibmu6S4OLIFg9U5FS+ttuRo4Faoyv13cHwIscj0QNLzlEFsYn7wGy/+qbmR0el1K1XTfxUoSPVK5NKrq/1YN8p8jMAHt397EGo6WYvt8Yoe11EyEsghOOoKbENZMNvhDOnqWzo3qV2SFF4xL8cMrFpKgFUSpUzUfGdNJbaKOpSncJgl11l2PShCxi4XVSwTH+N0b+rtAUDDrIDSGo6vhxxs3op1v7goksba/MTtE3pyD0CQL2d0dB5xqccmQngMVcGUk9W/EvM4CEsuEG+bXyJBL1VOLCCxKvw8STX4+uwNt2brDujIjSbVHZycclfzQULP4WY3rDvPmvm/lzcLqbedPhGRDYP3wMQXyLlqUBo21h0flximdXBEyFPMBtPWIj2FNgoSirwO6Hv8QnCgUGyrheg2lmbMY4dGtPh4C3AsBwZcU819mt4L4kpU0KKFDucW+agTLjPelyAH/gYrdM5VwvUuzuiDbOb0qsylSK1YMf
  template:
    metadata:
      name: newrelic-secret
      namespace: infrastructure
      annotations:
        reflector.v1.k8s.emberstack.com/reflection-allowed: "true"
        reflector.v1.k8s.emberstack.com/reflection-allowed-namespaces: "monitoring"
        reflector.v1.k8s.emberstack.com/reflection-auto-enabled: "true"
