---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: postgresql-secret
  namespace: infrastructure
  annotations:
    reflector.v1.k8s.emberstack.com/reflection-allowed: "true"
    reflector.v1.k8s.emberstack.com/reflection-allowed-namespaces: "workloads"
    reflector.v1.k8s.emberstack.com/reflection-auto-enabled: "true"
spec:
  encryptedData:
    postgresql-admin-password: AgAFEdoc9ka68asfZtV/SqhhzxOWTB/zFqv9hS8bhP43f9SYKk6713HDIZ4LxijeVEwfDcJ6ukkAF3aHTIXrf3YLSBj+AZHSgmK0K49X2EozAYxwKYneDpDY9dLrf/SReier7e7BVwjsXcCRLKSOehrRrrBif9FHvXA0zVzDs4J2Dz/7qpEvtY5RWSMoGLXApZywmYlPO5vyL2ldUulHVG7hkOu2I3jSV+TMoMrBfZrdBLmafqogJkc9ICWSeqRI2Drol/rZnffCwwz13HxtErE8nhZgsZHxasYxKI20a1q91AEgPW6nLvFrVN8EhZUW6OCsn7I+01d4Io3QKTkgHXwYja4sy0avIoNuIaMr2YsAqyvRbRIhPYn19hT05a0e3kPLjXzqbl7ajEOCZLij1c5m+CSs+ljlMT6L3BBP68KaEfx+fVW82tUJB4WmOVgXu3dF8FgrRxcnF/zPzex8NgisSM6efZC7E7C/1YDG20SYrQHVXNjtRKjFGkjemS03Mk06i9yip+4cmVmzph7Eco8g+K7uhKT16P7bl3ZsJgDiG+SyO9mWPRK1Naf17FxeADerIHwYBlnEsJGA1q9f++gCt4F8sTRRdSrJvzkslzSaNHYxxZHhGJERipkKIe9Vj44tio+oBA6QZ6yFtX+Voqi5jRNGZKKdvwm8VuG/s5FW88A0sYJhshDHKtjhZvR8hUbyJM/+AbUaNXXalt5BCw7J3Sgc9ZgLunKZrVmgDvi5JrQeuLLan0bJplCb7A==
    postgresql-immich-password: AgBdIpFbO7+BGqkSbXOlwHsWPyx+srM/QwzRK168bbpSzE6FDoDzmKR5wKuQZu1TLnJMOB4huXJovNq7HhIhZfeghr4wN3COLT7X0TfEd7vDhDsr2qBdeA4iZ+DT2EvRlcET9L+sNOYbOmUY3gRIh0QFYvQrZADi9PjUbxRSn3p8FuFfVHSFTV9yEvkC6lFd0YWXAltBW2H5NiUN16YKndlCkPsKfeF1sp0yvF+hc7H5lzAoT/Qh90fu1MnrJFy6sNV8Ep2i9pEKPDtn7nyVJ00Y2gtpTdIP4yY9AfQYtk5Jqv5Y1V2W5xrj1qCQGQsM2jmHiUFeOWDY168/p7Z60AE+Z9OyFLSvMIu6CQlOi2tdgihEJcojU9o7TwxPX80XMJDgPBEalbT3cV4siKJwX4IqhBrvHsSCGbcl4y8fDgOc0tYxNo6VB3S3LcsM3damS2edVT9uowrfRB4kEEHUCMQXG6OuYb95HXk8a6qoPtynNmi+unbBd0ceKUCQNktxySj3GuWH9+nVOmx5AnABQD09jdm8uaatQs8t8UIX6mf7VIjS8nR8jHKvBi+MAkP0H6YszbkgFun8x6Nt+vlVwnDq66RdU8K7m5Mwv50qxnt+u/olwoxNzZ28fhud26849kVZgmqs80lXLEYhVv25YIEb6Mo2fe4ruYdo3wfTYVziFJ3YoaV0xYh/zuntlAsH6bzqpg552b8kpJNSnaYFbCKhVpZxE733sRvLF3BZSiCu7Qz2vWY87wn88lpRFg==
  template:
    metadata:
      name: postgresql-secret
      namespace: infrastructure
      annotations:
        reflector.v1.k8s.emberstack.com/reflection-allowed: "true"
        reflector.v1.k8s.emberstack.com/reflection-allowed-namespaces: "workloads"
        reflector.v1.k8s.emberstack.com/reflection-auto-enabled: "true"
