---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: postgresql-secret
  namespace: infrastructure
  annotations:
    reflector.v1.k8s.emberstack.com/reflection-allowed: "true"
    reflector.v1.k8s.emberstack.com/reflection-allowed-namespaces: "database"
    reflector.v1.k8s.emberstack.com/reflection-auto-enabled: "true"
spec:
  encryptedData:
    postgresql-admin-password: AgBhyqk2ximsBkGoGiTluYTnpzqLwntFcpIs2A4RhXVMfLJBn6VuhBQlqDVSbg36XqtwV6sGQMtdnwiuC05wK7B9ogf1Gws0OJqHZMitY2pFSzaQFsqukJaW/xOAbNC94P2YaJdEmv53r4w+5Sy304o5WsQ3ugIj4aFUDxzSBCZ7vhgb3iL8TVkilNt+kvt85b/4CyDrO6m28GkcrFxzRkCaJUhinV5qm/nVPx7AbKO1HWYlCp/NKnEg2q1rUqoFQpTv7tmBjddIJU7f/OmTz5Na9+1aOQcQDr8ejfZXfz4ppK8eP5dK+xv4n+MYZb/j1KL/IEhGGjamwyHy6PXXytHe+zGxQARbYcILwQdNPN49kbZhxtoumRSW+oUVrnvglTTAK6F5Hc+HgG87EbDDmcfuxY1YxaxU+WxR9A1jobg0FBFPhNsGLZT6pYRIbM05dFE0buTKM7wPeNRIOQz8I66E2altsmQV9rIYMlD1swoUJ+lv3IaRh0ANJ7E3BoiuBU07d6tvBM7YOIInABLPcGunKsaebFsU/OhtDsGjpYXrRfK3RHm+yHiezaWfp6mtKbKyJB0IEH/qkYD6IBzboa/f8T70sOPvJNmYJJF1PQZnW405qZ6u/QjD1dUn+w6/NePOJj+H/DajmfwHmLXBQUJvyNpYdd42bFjeKkAjz3lRpi2dLdmja+zyxQNS4YWbcNmxQG+4MJ9FZzEFFEAwy362/htGj7KCRIRAD4tI33BBlBtdlvTOkUiQ0qZjhA==
    postgresql-immich-password: AgCYqroTsr4xsEdPwNQNMMxiIF48Ij1Ckn1L6ntJw+39lqbE25bHhXYRjaZjaAzbn+PU5tEJhsZCdCCltLcx9G137fDvX5seOCdBxs1vNdOWuIRpk1UiUMJ74cHYD64+CGqS3ptGTywEgYMLpanHtET2l+07XSsHAAGhmKwGwTeY+JFsqbEMAIrJYj1QbsvYf1P/VR+z9ZOuctl60h7scnktrsCV4j063OZSofrUHqH3xi6BUD8ABu97PCnmzAiIW65roJ5dDz95Y+6Uu0OXjUXLbc8CyCBoYnuW+ujCdy0MZi4pHe5m8UNhOlCymn3jmUrr/QKHJ152Sd6AqrSnMgDMJB651GDSRoau6n29j3dgOroFRpnIuhjd/4xI4HfNK+PU9fA3GmZ5+cG9u1sCjV9kh+RTxvcf1iun4WF0K8CutN+gKxMkL7VWQZo5Z2PYFlTYGP0qYbp+tgIWjjvbVoVjGv96vVgU2GZD6OREHHL2SYhZc23HCLf6lE3QPjqfykSVetl459jgAmPnRtacip3sukhzfXdu1G4K3eZJaen/mFpThjE2e1DW6pJX7NvaK6S1SsB4tEjHRDG3Ys+CUHQOubJOxdCgYqTHxypIOOh5+5Yf3jr3kOSkCVHMhpBJMY4PK7PZIadfabWQGfDEoo3/1k9NTBunRGA3zeFf2eTwPG6WDHB+4WI2Fg5yrTJ51nOqm4moifW1mZJxoXrApdKUoFFGOALtMI+I2SXtKQDANF6nrdmw+He+TmplrQ==
  template:
    metadata:
      name: postgresql-secret
      namespace: infrastructure
      annotations:
        reflector.v1.k8s.emberstack.com/reflection-allowed: "true"
        reflector.v1.k8s.emberstack.com/reflection-allowed-namespaces: "database"
        reflector.v1.k8s.emberstack.com/reflection-auto-enabled: "true"
