---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: tailscale-secret
  namespace: infrastructure
  annotations:
    reflector.v1.k8s.emberstack.com/reflection-allowed: "true"
    reflector.v1.k8s.emberstack.com/reflection-allowed-namespaces: "tailscale"
    reflector.v1.k8s.emberstack.com/reflection-auto-enabled: "true"
spec:
  encryptedData:
    client_id: AgB5myJAJkezS1ewCIbZSfzO4Zmc6RWoaMDB1Rp4oCv5CEEHASjfZWZOf2ZpSb6uYb1c20LOJQFfYkhoKiMwNcOcAZIMReRmhdFqkNUds9JXx60OJDY9POjU0pEmyFLezs5+wSJ3ne+NCzhszQER112t0aI+9DHzyIJsO7GKIsU/jPjAcS2eOk9uwZSBNCuQItvN23LDIJc5kVnNR2bUnRbMG6pHjr9jIiKKkD3lU0Gt8NsJy5jqYUti18C1GhxYGacy32mD1c8u3O8E+EXhJFQvn4FrJvTqKECsUoD7Wxcti9MmF8AUT90IxNcSwM5PNaVkEFBW+Ht1/Fd4IlvcPVj3hG+x7D70gsPBFy/p7pLmHuf5IwvYje3BdDU7z43U4nm0io/dJOZHKE1DDbolQDaadRNX4VQeVU1ZRHxuIBx7yCzItyaBfotQOAhKC3pZIRjI0w5Lgjpj58y3wDoFQEEQW039DxhJcfMRQXjr4BVBMowm5dsKMZNU3SCbCkV4Tt73WDkqDdMUGLi1jBFdF4D4bf+BlWSymuP0PY7HWZPMr0TkslfzdVWvQxhyq1SIV6EChTgrEO6/2dyuRGyPAzMR6ZShMyt4AJBfNhaNy1O+UaMse38uK8yeA5YBCrlH0Xf7aSz04jLP/GsmkZ7H82IMSQRe7EAEWO21ugwNPFxiXljYImR2LPqoi0Ku1RkKWemV0o16Q7rMjBLPO0FqOE714w==
    client_secret: AgAaiBUNK9HZgmMUv79+4DXTUV63RMEs1s4JZGMMxO3WvTVbLygC8ArJCwD/3KNDDzZCn8dh9+L7BNGH5kG2ELTCwtBEuEpwarylclOKDYQB+u4v1qDCNyXG8CM++vI2cH1xlTyitPq4BVQDyLB8WsEdUQXOs01ev+Jk0fmHnkFKkIutSb0ENs65WN7nuOB/ifk3UmWc4qjR4FwD8EJeAhW6jhXMV2egReQpltLlNecXVjCub/Q3flux3c8pEOCT8qQTrPzZD+0NGQ7ANyNUTemGukTkIk9DgD4d8Iqu36Waj/9Xxy3HHdGzmX3oVGht/S54Fe2wFC8YGkd1oJc+PAQgVaP+SkVLSY3lDMFpwo557RQiW/ClrwfHbMpEWFiXLJM4YX7k4OrN+q7iE8cRG80u923Gim4F1X723J0FqPaai8I22Vx28BbiXCbXch1bkKpmHL+J7YOE33JIsOOE/bBm6LGTZVbe8Pz8FUREnGlgZhJ4u2tc0bmq10v2yuZAJAfLKqgyVPr3uE+vJZqABrAdBw5+B6EdNhN+I+o3zHIYbAp1YAM43iddZmOdGhvPgJbie27ry/8pWwe7pkUQ7VgCwEENNg21J+PbxJYHCK+TgseDqYclittLxE7W6RrMPtb9VyeDuYVAn6PKWn8wDRQIzfm+jwplNDyDNifUx/uTqNpWF/bVX2Sa4Iqa37reAqfCJiyeJxONog4+0eXYlnZlUU5XY3eHKQWFqI8fKnJSc+SQBX4dYSRAz6w+dg6VwaI/TYuWpAhhLD8o6Kb8Onw=
  template:
    metadata:
      name: tailscale-secret
      namespace: infrastructure
      annotations:
        reflector.v1.k8s.emberstack.com/reflection-allowed: "true"
        reflector.v1.k8s.emberstack.com/reflection-allowed-namespaces: "tailscale"
        reflector.v1.k8s.emberstack.com/reflection-auto-enabled: "true"
