---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: tailscale-secret
  namespace: infrastructure
  annotations:
    reflector.v1.k8s.emberstack.com/reflection-allowed: "true"
    reflector.v1.k8s.emberstack.com/reflection-allowed-namespaces: "tailscale"
    reflector.v1.k8s.emberstack.com/reflection-auto-enabled: "true"
spec:
  encryptedData:
    client_id: AgAJ27Alq+4e0/w7hDR2rcRfuIiR/lg+/U2vv3naV7f6TWq1A7ybyCNYNQW9PS0zHhsbM6TUScF1RARrQ05aD1Uf9tu+L0hGsQA8Hu+fEua0tsqIlJPYcy/UygYXUNMtnjYHiMr1mOR2ZQnOZMnn+hwghP9+I7yPgcCd01vaM0TqXdlwDF3ll1eYEZv26Syc8EDCa7JTlWoYxN3xdFt6E+x4yGOc5iaRFR0TujIM6ljUvsTlRz4+YgiR3vOkzbpbB6zMHy0BYydrx6ECrvdRGyS3Ob5TdaV4WPidKDF6TGkvU3f9rhiITNVuWC5meMuXmZ2yoHxbmxh4MLDIBgqIcJPPE2/tAJsjSCwSu80w5CdJcPW6FXsoBjnGm23Q0z5p/kGlUf8tZayOnI/xd8bw2wNQ4EK11CXCrkyP2X0UPJlyHkr8e9Ukiw7PylksqJm8d25SuRn52rWOQ9XqEKGKzPFYnJNB9JCilq20SoBMO7UPAtZmPF19BKaCvuzr0H1QcicHDqftadPLxDNrgFHO862ktHKQgP0Ge1JMN1+T/VagMva1SEp/vxreN7ZLrGdYbYXk1zQP/O/OeYnNI0TQG+IrWEJN88KbGyPRWCgJYTU/O3OT1dPpeVS06O4/MS5BHUUA1vSQOVqF1aJj7jGVhx11KDYfnRsOq72Kb6PySNIb3gkuOEEcjdpKtSCOpWNBU28BFjSPlWfi30mmzByS3yq5nQ==
    client_secret: AgBBJN6erAnN383My4h8SSfDWOSLJJEgePNQhJt/MSN0QA/2TuJhh33LjYhCTMFnZV7JccONnUkkJs7EO1Ok+233Onm5FbWyl3BsM9n0KeSBRtq4alohUu1AzqbB1QhuMhTWlYHG/gbUej2Z0sl2OFeAXryaQJr/dbRp9vD461d8nF1uBjvlAVJDsu/IYfgHgpm2TVA1XAMKtOKjx/eSRQU9cIdp/4GQ0Zyej/FpvCNe9bmJB1VpZdy2mjAPSP6I1B1TUf7JwILGMTp6ZNzN0RjIZERFTkeOEDqsODyCd0H/zamMXjjPTxiEmSD0hADwwa2R4JaUf6y/dLEKYz6/is7Cql8DzTsN9gfiPJWGqRYJPbQp90QxMCK/7kc38zw3Tap4WuAWG1rEanaBu5q1GkP/DtuUPlkELdTBw+oeIAz0y7X5hazC/bwjN6o0kJ2ozzn9G8stmzSqjur45XNppl5NRDSttGgnPKdNm9xHhiu/vCXf7uBGVG4NkmZPiaeF0IKnXTua8v4Lb4S/X1goGiDVDj0J4GIsPC5v2v8lWc0oM/t4lIL1g4pmbv+Wa0KyrBmPkKKlhHFqZMHaJd4KgpzC+4HXQ0wRhjWywjx9JwZsSMxcVsqAa5XRr7ReDAFYcOeYIVKQ3AYU5qUYq3mPaiyxQMw37ck2fdZ8dHlccjQzZImaWha5NsebMeTq3Fpvx8DIesNSzxncEzKXYkzzOLYcnWeO5O8/lprnmY4U7LOMKPxdjZfrmYBpFn4hXXq8jjkXDzTDDDT8Aq5EWjNTagLD
  template:
    metadata:
      name: tailscale-secret
      namespace: infrastructure
      annotations:
        reflector.v1.k8s.emberstack.com/reflection-allowed: "true"
        reflector.v1.k8s.emberstack.com/reflection-allowed-namespaces: "tailscale"
        reflector.v1.k8s.emberstack.com/reflection-auto-enabled: "true"
