---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: traefik-dashboard-secret
  namespace: infrastructure
  annotations:
    reflector.v1.k8s.emberstack.com/reflection-allowed: "true"
    reflector.v1.k8s.emberstack.com/reflection-allowed-namespaces: "traefik"
    reflector.v1.k8s.emberstack.com/reflection-auto-enabled: "true"
spec:
  encryptedData:
    users: AgCZAljL9vWh8+wC+8lm0nPkf/7dkiWcQAJALlFx0v/9HJ+uiEQA5HuClLLIA7Ilw0qLoCFPoUW1jNN02fCT0AdTylA/TW2ho6u5FbDSWhYSgRmbF0UAUPcxuZfewXV9GIHOmynvFX0NZ5rgLPxPosNlukgcpe9O1rRuNXYqn/QUpKmkyHjRcCno6zKEL3pBHvc2GCKjPR2S9jAXHwMFn0ROfm2kKjj3XRaxFZii1yIL4O3C8VUcd76wqZ3cI7qy+vy8ENMW2LQXEuXbEcj+qOm8q+FQgrPBoX+9EIrLPXDvHTYquiqv5umO/e4yPl8s5zLPfCNVKECNSpGpp27m6jRkmb2hJMNJrUxUpgv2U4Gn7ZbL2iDLcRnCh2ZvrZwU7C7kpIgr1+E4A6B1bqGYibFSEbfpfBoDb/tpuNkhERz/ndHa9sXHSH0buJJWNZddmHA0RSpjcDevdLdbHrYJth9ri0DLaTqWwJHYVYf1NvjqG3aEsw7ngh6yG0vNlDhIX9ayjVCBKDe4J4jD9TvCvBIWP3ECAgeTTFxLve7zEyUse9YA/rgX/ApTI7590+/nqaDcTn/rfswx2hgj3LMRTESE6VS2OCJSsbIOjzitgAiGYhB5yN352kMurxvOUSM4RQtR59I79axiV+XAWVLxl40llfZ4PhriiFxeqoLeEzNBogu2dk6fPhR4S7wFbMlEyBtHFSuYs10XvJFPls6qXYJeIPUqm6RqY1x5lCH3d1SddNcdZOHdGtk=
  template:
    metadata:
      name: traefik-dashboard-secret
      namespace: infrastructure
      annotations:
        reflector.v1.k8s.emberstack.com/reflection-allowed: "true"
        reflector.v1.k8s.emberstack.com/reflection-allowed-namespaces: "traefik"
        reflector.v1.k8s.emberstack.com/reflection-auto-enabled: "true"