---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: traefik-dashboard-secret
  namespace: infrastructure
  annotations:
    reflector.v1.k8s.emberstack.com/reflection-allowed: "true"
    reflector.v1.k8s.emberstack.com/reflection-allowed-namespaces: "traefik"
    reflector.v1.k8s.emberstack.com/reflection-auto-enabled: "true"
spec:
  encryptedData:
    users: AgAkp128HZepbqwwqChmK2sjsjFjjtuuYnEO8Neh97R0K7pLZAv/qaA3DTe3z745CoI4/M99UFGaRRiiX0Zz5nTM98s4wB1PO/z4njPuVFzSmTw0FMmnd1LrKbiAMo7QSpzOHvNAZtlYph8tbq+anwMwYb4r/jEFWyP2vDF6grTeVmc3ueaT10qPO1aGQUPn9r4LmBmTHWZRrtUo6qkewBDfn1+d4AUC85S0qoMZaC7xbOGdMIMsUCeF9DsGu1dH7dpDJPtKAqESxTXBiouSX8siwoToi2g9XkWmisyZlpd6vKpNQKdsXL5hWLtiB3EH++1Nt84UuTz7F9EaiHKAYuMwNGaRoMVmtOtTosu/Vh2276W+P0kD5KUffY/GxIz+Lsun6KatcvhVtY9o/AldmZV4rRRmDF/vu2y7Biaib4YcZQR/Z0/RJ65joN1vgmXL2FVp1sY6w8/7i+t1L0QTFwzoQunGXPuhT9rWt8otfqgLFzA7zcGiwLQgAJO0FpTCADQx5+VjtmU3LVVScPiP0AS0Hw6fzZSyx+BumBDFv7+Wbo3I8/KN8H3z7vmIDUNLERXEWLdXsfL4+IEg8elwwZawNcFgC6czsCmof/sycgZT/o3KsSHkEb1fOTIbWG0tUsOx0jGRLnqI9cl0hyO04+HJ3BsHf9to8I34mpGC7++U2bN8Z6cjGKk5U0xLsx4gnMuml4dXV5qTmAqQypAnvn5XKq5q8RDOGt7YM48yw2i+YesxdQqpzZ4=
  template:
    metadata:
      name: traefik-dashboard-secret
      namespace: infrastructure
      annotations:
        reflector.v1.k8s.emberstack.com/reflection-allowed: "true"
        reflector.v1.k8s.emberstack.com/reflection-allowed-namespaces: "traefik"
        reflector.v1.k8s.emberstack.com/reflection-auto-enabled: "true"
