replicaCount: 1

imagePullSecrets:
  - name: infra-docker-config

image:
  repository: ghcr.io/schmhj/microservice-template
  pullPolicy: IfNotPresent
  tag: "v0.0.6"
  
service:
  type: NodePort
  port: 32056

# OpenTelemetry Collector configuration for receiving OTLP and exporting to Grafana Cloud
otelCollector: "grafana-alloy.monitoring.svc.cluster.local"