oauth: {}

oauthSecretVolume:
  secret:
    secretName: tailscale-secret

installCRDs: true

operatorConfig:
  image:
    repository: docker.io/tailscale/k8s-operator
    tag: v1.98.5
    pullPolicy: Always
  logging: "info"
  hostname: "tailscale-operator"
  nodeSelector:
    kubernetes.io/os: linux

ingressClass:
  name: "tailscale"
  enabled: true

proxyConfig:
  image:
    repository: docker.io/tailscale/tailscale
    tag: v1.98.5
  defaultTags: "tag:k8s"
  firewallMode: auto

apiServerProxyConfig:
  mode: "false"
  allowImpersonation: "false"
