apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../prod
  # - immich-ingress-route.yaml
patches:
  - target:
      kind: Deployment
      name: traefik
      namespace: traefik
    path: tolerations-patch.yaml
