apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: newrelic-bundle-nrk8s-kubelet
  namespace: monitoring
spec:
  template:
    spec:
      containers:
        - name: kubelet
          env:
            - name: NRI_KUBERNETES_CLUSTERNAME
              value: oke-tenant-a
        - name: agent
          env:
            - name: CLUSTER_NAME
              value: oke-tenant-a
