apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../prod

configMapGenerator:
  - name: grafana-alloy
    namespace: monitoring
    behavior: merge
    files:
      - workloads.alloy

generatorOptions:
  disableNameSuffixHash: true

patches:
  - target:
      kind: DaemonSet
      name: grafana-alloy
      namespace: monitoring
    path: run-dir-patch.yaml
