apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonAnnotations:
  argocd.argoproj.io/sync-wave: "2"
helmCharts:
  - name: sealed-secrets
    repo: https://bitnami-labs.github.io/sealed-secrets
    version: "2.18.3"
    namespace: infrastructure
    releaseName: sealed-secrets
    includeCrds: true
    valuesFile: values.yaml
      
